spring:
  main:
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_schema
    username: root
    password: admin

bot:
  name: Computer shop ZKS-21
  token: 5934201310:AAFUii1hwaKzDrfoKF8Sq8EX_mROR3MVL20

