name: Cleanup Old Artifacts

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Remove old artifacts
        run: |
          date_threshold=$(date -d "30 days ago" +%Y-%m-%dT%H:%M:%SZ)
          
          old_artifacts=$(gh api repos/:owner/:repo/actions/artifacts --paginate | jq --arg date_threshold "$date_threshold" '.artifacts[] | select(.created_at < $date_threshold) | .id')
          
          for artifact in $old_artifacts; do
            gh api repos/:owner/:repo/actions/artifacts/$artifact --method DELETE
          done
